### PR TITLE
Add terraform-provider-gitlab public signing key

### PR DESCRIPTION
**Pull request by timofurrer**
This is the public signing key for the GitLab Terraform provider:

- https://github.com/gitlabhq/terraform-provider-gitlab/releases

### CODE REVIEW

**Comment by Yantrio** [comment]
Thanks for your contribution! <3

**Review by Yantrio — APPROVED** [review]

**Comment by timofurrer** [comment]
@Yantrio is there something missing that I'm still getting that the signature cannot be validated:

```
./tofu init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of gitlabhq/gitlab...
- Installing gitlabhq/gitlab v16.4.1...
- Installed gitlabhq/gitlab v16.4.1. Signature validation was skipped due to the registry not containing GPG keys for this provider

OpenTofu has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that OpenTofu can guarantee to make the same selections by default when
you run "tofu init" in the future.

OpenTofu has been successfully initialized!

You may now begin working with OpenTofu. Try running "tofu plan" to see
any changes that are required for your infrastructure. All OpenTofu commands
should now work.

If you ever set or change modules or backend configuration for OpenTofu,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by Yantrio** [comment]
Hi @timofurrer small oversight on my part here. We match keys based on the org owner.

In this case the org owner is `gitlabhq` and not `gitlab`. I'll put in a pull request to rename and then I'll deploy this straight away for you

**Comment by timofurrer** [comment]
Ah, that makes sense, thanks!

**Comment by Yantrio** [comment]
Hi @timofurrer this is now resolved in #143  and deployed to the registry 🎉 

Thanks for raising this. Please try again.

For reference. Here it is working on my system now 

image


If you hit any other issues feel free to reach out or raise an issue in this repo! thanks <3

**Pull request merged**
