### PR TITLE
Upload GPG key for Oracle

### PR DESCRIPTION
**Pull request by jiaqchenO**

### CODE REVIEW

**Comment by Yantrio** [comment]
Hi @jiaqchenO, thank you very much for this contribution of the GPG key.

Would you be able to rename the folder you're pushing to to match the organisation name please? In this case I believe it would be `oracle`?

Thanks 🙏

**Comment by jiaqchenO** [comment]
Sure. I already renamed the dictionary name. Thanks a lot for your help! @Yantrio

**Comment by Yantrio** [comment]
Hi @jiaqchenO, I noticed that the creation date of this gpg key was `createdAt: "Thu Sep 21 2023 20:52:03 GMT+0100 (British Summer Time)"`.

Would you be able to upload the gpg key that was used to sign the provider artifacts instead please?

These keys are to be used to validate the signatures, and not to be used to re-sign

**Comment by Yantrio** [comment]
Hi @jiaqchenO, I can validate that these are the correct gpg keys 🙌 Thank you for your contribution!

**Review by Yantrio — APPROVED** [review]

**Pull request merged**
